name: coffee_dice
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.1+3  # Was 1.2.0+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  # Using Cupertino icons for iOS style
  cupertino_icons: ^1.0.8
  # Add this line:
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  audioplayers: ^6.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # This helps keep your code clean
  flutter_lints: ^3.0.0
  # This is the tool for your app icon
  flutter_launcher_icons: ^0.13.1

# Configuration for the App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/coffeedice_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/audio/